### ISSUE TITLE
Task List (Init:1.0,02,23,22)

### ISSUE THREAD

**Issue by RechtDev** [RechtDev/MVCOrderManagmentUi#1]
- [x] Restyle Create Product page. Create Product Page should have
     - [x] Each input needed for a product.
     - [x] The input for product type should have a drop-down menu showing existing product types, while allowing the user to  type in a new one. The list should allow the user to select the item and fill the input form.
     - [x] Styling should be uniform and coherent on this page and the form should be centered in the middle of the screen.
