### ISSUE TITLE
Task List (Init:2.0,02,23,22)

### ISSUE THREAD

**Issue by RechtDev** [RechtDev/MVCOrderManagmentUi#3]
- [x] Create a search bar for Products Page:
- [x] should be in between the Product name and Product price columns 
- [x] Needs to have a meaningful icon beside it to signfy to users that this is a search bar.
- [x] Needs to be responsive and not a server action. JS should be used to create this functionality. 0-page reloads needed to show results
- [x] Default styling for this search bar should be overridden to match the pages/websites theme.
