### ISSUE TITLE
Login Auth Form Task List (Init:3.0,02,23,22)

### ISSUE THREAD

**Issue by RechtDev** [RechtDev/MVCOrderManagmentUi#4]
Add login form for the initial entry of the website

- [x] Login should provide basic functionality (UserName, Password)
- [x] Manually accessing a route via address bar should redirect the user to the login if not already signed in
- [ ] passwords should be hashed+salted before sending upstream
- [ ] passwords should never be brought & stored downstream only used to compare entered version against
